title: BLP Rounds
description: Media feed from <a href="https://bermaguilocalpost.org" target="_blank" rel="noopener noreferrer">Bermagui Local Post</a>'s deliveries
publisher: Bermagui Local Post
publisher_website: https://bermaguilocalpost.org
copyright: All media (images, videos etc) published in BLP Rounds is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="noopener noreferrer license">CC BY-SA 4.0 International</a>. Bermagui Local Post&#x2122;, BLP&#x2122; and the BLP logo are trademarks of Miro Jones.
url: https://rounds.bermaguilocalpost.org
timezone: Australia/Sydney
plugins:
  - jekyll-minifier
