title: BLP Rounds
tagline: Media feed from Bermagui Local Post's deliveries
publisher: Bermagui Local Post
publisher_website: https://bermaguilocalpost.org
copyright: All media published in BLP Rounds is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="noopener noreferrer license">CC BY-SA 4.0 International</a>.

url: https://rounds.bermaguilocalpost.org
timezone: Australia/Sydney