title: BLP Rounds
description: Media feed from Bermagui Local Post's deliveries
description_html: Media feed from <a href="https://bermaguilocalpost.org" target="_blank" rel="noopener noreferrer">Bermagui Local Post</a>'s deliveries
publisher: Bermagui Local Post
publisher_website: https://bermaguilocalpost.org
copyright: All media (images, videos etc) published in BLP Rounds is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="noopener noreferrer license">CC BY-SA 4.0 International</a>. Bermagui Local Post&#x2122;, BLP&#x2122;, Rounds&#x2122; and associated logos are trademarks of Miro Jones.
url: https://rounds.bermaguilocalpost.org

plugins:
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true # enables experimental ES6 minification

favicon:
  source: /assets/favicons/favicon.svg
